version: '3'

services:
  app:
    build: .      
    depends_on:
      db:
        condition: service_healthy
    container_name: app
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules # Volume anônimo - garante que o diretório node_modules dentro do container não seja sobrescrito pelo conteúdo do host
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: nginx
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullcycle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork:
    driver: bridge
