version: '3'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullcycle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork:
    driver: bridge
